---
language: node_js
node_js: 12

sudo: required
dist: trusty

addons:
  chrome: stable

stages:
  - test

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install --non-interactive

script:
  - yarn test

jobs:
  include:
    - stage: test
      name: Tests
      script:
        - yarn test
    - stage: test
      name: Lint
      script:
        - yarn lint
